version: "3.9"

services:
  app:
    build: .
    container_name: toyshop_app
    ports:
      - "8085:8085"   # доступно на http://localhost:8085
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/toyshop
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

