spring:
  webflux:
    static-path-pattern: "/uploads/**"
  application:
    name: toyshop
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/toyshop
    username: your_userName
    password: your_userPassword
  sql:
    init:
      mode: never   # для R2DBC не работает jdbc-инициализация
  data:
    r2dbc:
      repositories:
        enabled: true
server:
  port: 8085
