spring:
  webflux:
    static-path-pattern: "/uploads/**"
  application:
    name: toyshop
  r2dbc:
    # для для локального запуска приложения (на Виндовс) на встроенном сервлет-контейнере Spring Boot
    # url: r2dbc:postgresql://localhost:5432/toyshop

    # для запуска внутри контейнера Докер и обращанием к БД на Виндовс
    # url: r2dbc:postgresql://db:5432/toyshop
    url: r2dbc:postgresql://host.docker.internal:5432/toyshop
    username: your_userName
    password: your_userPassword
  sql:
    init:
      mode: never   # для R2DBC не работает jdbc-инициализация
  data:
    r2dbc:
      repositories:
        enabled: true
server:
  port: 8085
